# Generated by Django 3.2.25 on 2024-11-18 11:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('birthDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('birthPlace', models.CharField(max_length=300, null=True)),
                ('nationality', models.CharField(choices=[('Cameroon', 'Cameroon'), ('Kenya', 'Kenya'), ('Nigeria', 'Nigeria'), ('Gabon', 'Gabon'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Central African Republic', 'Central African Republic'), ('Congo Republic', 'Congo Republic'), ('Democratic Republic of Congo', 'Democratic Republic of Congo'), ('Ghana', 'Ghana'), ('Togo', 'Togo'), ('Senegal', 'Senegal'), ('Guinea', 'Guinea')], default='Kenya', max_length=300, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='studentImages/')),
                ('town_name', models.CharField(max_length=300, null=True)),
                ('road_name', models.CharField(max_length=300, null=True)),
                ('previous_school', models.CharField(max_length=300, null=True)),
                ('level', models.CharField(choices=[('Reception', 'Reception'), ('PP1', 'PP1'), ('PP2', 'PP2'), ('Grade1', 'Grade 1'), ('Grade2', 'Grade 2'), ('Grade3', 'Grade 3'), ('Grade4', 'Grade 4'), ('Grade5', 'Grade 5'), ('Grade6', 'Grade 6'), ('Grade7', 'Grade 7'), ('Grade8', 'Grade 8'), ('Grade9', 'Grade 9')], max_length=200, null=True)),
                ('transport', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=200, null=True)),
                ('opt_services', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mother_name', models.CharField(max_length=200, null=True)),
                ('father_name', models.CharField(max_length=200, null=True)),
                ('guardian_name', models.CharField(max_length=200, null=True)),
                ('father_phone', models.CharField(max_length=10, null=True)),
                ('mother_phone', models.CharField(max_length=10, null=True)),
                ('guardian_phone', models.CharField(max_length=10, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('registration_agent', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
