# Generated by Django 3.2.25 on 2024-11-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthPlace',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Cameroon', 'Cameroon'), ('Kenya', 'Kenya'), ('Nigeria', 'Nigeria'), ('Gabon', 'Gabon'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Central African Republic', 'Central African Republic'), ('Congo Republic', 'Congo Republic'), ('Democratic Republic of Congo', 'Democratic Republic of Congo'), ('Ghana', 'Ghana'), ('Togo', 'Togo'), ('Senegal', 'Senegal'), ('Guinea', 'Guinea')], default='Kenya', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='road_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='town_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
