# Generated by Django 3.2.25 on 2024-11-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='opt_services',
            new_name='optional_services',
        ),
    ]
