# Generated by Django 3.2.25 on 2024-11-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_opt_services_student_optional_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='option_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
