# Generated by Django 3.2.25 on 2024-11-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student_option_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='optional_services',
            new_name='optional_services_required_for_your_child',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='option_services',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_level',
            field=models.CharField(default='Grade 1', max_length=200, null=True),
        ),
    ]
