# Generated by Django 3.2.25 on 2024-11-23 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20241123_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthDate',
            field=models.DateTimeField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthPlace',
            field=models.CharField(max_length=200, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_phone',
            field=models.CharField(max_length=30, null=True, verbose_name="Mother's Phone Number"),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Guardian's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(max_length=30, null=True, verbose_name="Guardian's Phone Number"),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(max_length=30, null=True, verbose_name="Father's Phone Number"),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='studentImages/', verbose_name="Student's picture"),
        ),
    ]
