# Generated by Django 3.2.25 on 2024-11-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20241124_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_history',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
