# Generated by Django 3.2.25 on 2024-11-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20241124_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.IntegerField(blank=True, default=0, verbose_name='Payment in Ksh'),
        ),
    ]
