# Generated by Django 3.2.25 on 2024-11-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_student_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_history',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
