# Generated by Django 3.2.25 on 2024-11-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_student_payment_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_history',
            field=models.TextField(blank=True),
        ),
    ]
