# Generated by Django 3.2.25 on 2024-12-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20241125_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('girl', 'Boy'), ('boy', 'Girl')], default='Girl', max_length=200, null=True, verbose_name='Gender * '),
        ),
    ]
