# Generated by Django 3.2.25 on 2024-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city_name',
            field=models.CharField(blank=True, default='Nairobi', max_length=200, null=True, verbose_name='City Name * '),
        ),
    ]
