# Generated by Django 3.2.25 on 2024-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_student_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.CharField(blank=True, choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=200, null=True, verbose_name='Term * '),
        ),
        migrations.AlterField(
            model_name='student',
            name='city_name',
            field=models.CharField(blank=True, default='Nairobi', max_length=200, null=True, verbose_name='City Name '),
        ),
        migrations.AlterField(
            model_name='student',
            name='transport',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='No', max_length=200, null=True, verbose_name='Transport * '),
        ),
    ]
