# Generated by Django 3.2.25 on 2024-12-02 22:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20241202_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_baba',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
