# Generated by Django 3.2.25 on 2024-12-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_student_payment_baba'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
