# Generated by Django 3.2.25 on 2024-12-03 04:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_student_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_baba',
            field=ckeditor.fields.RichTextField(blank=True, default='ya lass'),
        ),
    ]
