# Generated by Django 3.2.25 on 2024-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_student_payment_baba'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_ID',
            field=models.CharField(default='SK0001KM24', max_length=10, verbose_name='Student ID'),
        ),
    ]
