# Generated by Django 3.2.25 on 2024-12-03 06:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_baba',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
