# Generated by Django 3.2.25 on 2024-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_student_payment_baba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Student ID'),
        ),
    ]
