# Generated by Django 3.2.25 on 2024-12-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.CharField(max_length=10, null=True, verbose_name='Student ID'),
        ),
    ]
