# Generated by Django 3.2.25 on 2024-12-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='system_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Student ID'),
        ),
    ]
