# Generated by Django 3.2.25 on 2024-12-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.CharField(blank=True, default='SK<django.db.models.fields.AutoField>', max_length=10, null=True, verbose_name='Student ID'),
        ),
    ]
