# Generated by Django 3.2.25 on 2025-01-03 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0033_student_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MPESA', 'MPESA'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], default='MPESA', max_length=100, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Previous School '),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registration Staff'),
        ),
    ]
