# Generated by Django 3.2.25 on 2025-01-05 03:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20250103_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_baba',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_history',
        ),
        migrations.AddField(
            model_name='student',
            name='last_update',
            field=models.TextField(blank=True, verbose_name='Last Update'),
        ),
        migrations.AddField(
            model_name='student',
            name='update_history',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Update History'),
        ),
    ]
